#ifndef __PHYCONST_H__
#define __PHYCONST_H__

#include "cocos2d.h"
/* 定义与物理属性相关的常数 */

// 各类物体的碰撞bitflag
#define PLAYER_CATEGORYBITMASK  (1u << 1)
#define NPC_CATEGORYBITMASK     (1u << 2)
#define GROUND_CATEGORYBITMASK  (1u << 3)
#define ITEM_CATEGORYBITMASK    (1u << 4)
#define STONE_CATEGORYBITMASK   (1u << 5)

#define PLATER_CONTACTTESTBITMASK (GROUND_CATEGORYBITMASK | STONE_CATEGORYBITMASK)
#define PLAYER_COLLISIONBITMASK   (GROUND_CATEGORYBITMASK)

#define GROUND_CONTACTTESTBITMASK (PLAYER_CATEGORYBITMASK | ITEM_CATEGORYBITMASK)
#define GROUND_COLLISIONBITMASK   (PLAYER_CATEGORYBITMASK | NPC_CATEGORYBITMASK\
                                   | GROUND_CATEGORYBITMASK | STONE_CATEGORYBITMASK)

#define NPC_CONTACTTESTBITMASK    (0)
#define NPC_COLLISIONBITMASK      (GROUND_CATEGORYBITMASK)

#define ITEM_CONTACTTESTBITMASK    (GROUND_CATEGORYBITMASK | NPC_CATEGORYBITMASK)
#define ITEM_COLLISIONBITMASK      (0)

#define STONE_CONTACTTESTBITMASK    (PLAYER_CATEGORYBITMASK)
#define STONE_COLLISIONBITMASK      (GROUND_CATEGORYBITMASK)

#define ALL_CATEGORYBITMASK       (0xffffffff)
#define ALL_CONTACTTESTBITMASK    (0xffffffff)
#define ALL_COLLISIONBITMASK      (0xffffffff)

/* 定义各类物理材质的属性 */

const cocos2d::PhysicsMaterial MY_PHYSICSBODY_MATERIAL_DEFAULT(0.0f, 0.0f, 0.0f);
const cocos2d::PhysicsMaterial MY_PHYSICSBODY_MATERIAL_FRICTION(0.0f, 0.0f, 100.0f);


/* 定义各类子弹的飞行速度 */

#define MONKEY_BO_BULLET_SPEED  (800)
#define FORT_BULLET_SPEED       (600)

#endif
