#ifndef __PHYCONST_H__
#define __PHYCONST_H__

/* 定义与物理属性相关的常数 */

// 各类物体的碰撞bitflag
#define PLAYER_CATEGORYBITMASK 1
#define NPC_CATEGORYBITMASK    2
#define GROUND_CATEGORYBITMASK 4

#define PLATER_CONTACTTESTBITMASK (GROUND_CATEGORYBITMASK)
#define PLAYER_COLLISIONBITMASK   (GROUND_CATEGORYBITMASK)

#define GROUND_CONTACTTESTBITMASK (PLAYER_CATEGORYBITMASK)
#define GROUND_COLLISIONBITMASK   (PLAYER_CATEGORYBITMASK | NPC_CATEGORYBITMASK | GROUND_CATEGORYBITMASK)

#define NPC_CONTACTTESTBITMASK    (0) 
#define NPC_COLLISIONBITMASK      (GROUND_CATEGORYBITMASK)

#endif
